/*
* @Author: kuychaco
* @Date:   2015-06-07 14:42:36
* @Last Modified by:   kuychaco
*/

'use strict';

var issues = [
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/6",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/6/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/6/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/6/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/6",
  "id": 86269811,
  "number": 6,
  "title": "Create JSON Object",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [ ],
  "state": "open",
  "locked": false,
  "assignee": {
  "login": "Berkana",
  "id": 1445825,
  "avatar_url": "https://avatars.githubusercontent.com/u/1445825?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Berkana",
  "html_url": "https://github.com/Berkana",
  "followers_url": "https://api.github.com/users/Berkana/followers",
  "following_url": "https://api.github.com/users/Berkana/following{/other_user}",
  "gists_url": "https://api.github.com/users/Berkana/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Berkana/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Berkana/subscriptions",
  "organizations_url": "https://api.github.com/users/Berkana/orgs",
  "repos_url": "https://api.github.com/users/Berkana/repos",
  "events_url": "https://api.github.com/users/Berkana/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Berkana/received_events",
  "type": "User",
  "site_admin": false
  },
  "milestone": null,
  "comments": 0,
  "created_at": "2015-06-08T17:41:50Z",
  "updated_at": "2015-06-08T22:30:47Z",
  "closed_at": null,
  "body": "Create node objects with appropriate issue or cluster data"
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/5",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/5/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/5/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/5/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/5",
  "id": 86269541,
  "number": 5,
  "title": "Delete Record",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [ ],
  "state": "open",
  "locked": false,
  "assignee": {
  "login": "cwhwang1986",
  "id": 8173733,
  "avatar_url": "https://avatars.githubusercontent.com/u/8173733?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/cwhwang1986",
  "html_url": "https://github.com/cwhwang1986",
  "followers_url": "https://api.github.com/users/cwhwang1986/followers",
  "following_url": "https://api.github.com/users/cwhwang1986/following{/other_user}",
  "gists_url": "https://api.github.com/users/cwhwang1986/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/cwhwang1986/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/cwhwang1986/subscriptions",
  "organizations_url": "https://api.github.com/users/cwhwang1986/orgs",
  "repos_url": "https://api.github.com/users/cwhwang1986/repos",
  "events_url": "https://api.github.com/users/cwhwang1986/events{/privacy}",
  "received_events_url": "https://api.github.com/users/cwhwang1986/received_events",
  "type": "User",
  "site_admin": false
  },
  "milestone": null,
  "comments": 0,
  "created_at": "2015-06-08T17:41:08Z",
  "updated_at": "2015-06-08T22:30:57Z",
  "closed_at": null,
  "body": "Remove nodes from database"
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/4",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/4/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/4/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/4/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/4",
  "id": 86269457,
  "number": 4,
  "title": "Update Record",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [ ],
  "state": "open",
  "locked": false,
  "assignee": {
  "login": "JustinWebb",
  "id": 442978,
  "avatar_url": "https://avatars.githubusercontent.com/u/442978?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/JustinWebb",
  "html_url": "https://github.com/JustinWebb",
  "followers_url": "https://api.github.com/users/JustinWebb/followers",
  "following_url": "https://api.github.com/users/JustinWebb/following{/other_user}",
  "gists_url": "https://api.github.com/users/JustinWebb/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/JustinWebb/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/JustinWebb/subscriptions",
  "organizations_url": "https://api.github.com/users/JustinWebb/orgs",
  "repos_url": "https://api.github.com/users/JustinWebb/repos",
  "events_url": "https://api.github.com/users/JustinWebb/events{/privacy}",
  "received_events_url": "https://api.github.com/users/JustinWebb/received_events",
  "type": "User",
  "site_admin": false
  },
  "milestone": null,
  "comments": 0,
  "created_at": "2015-06-08T17:40:55Z",
  "updated_at": "2015-06-08T22:31:03Z",
  "closed_at": null,
  "body": null
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/3",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/3/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/3/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/3/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/3",
  "id": 86269344,
  "number": 3,
  "title": "Read Record from Database",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [ ],
  "state": "open",
  "locked": false,
  "assignee": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "milestone": null,
  "comments": 0,
  "created_at": "2015-06-08T17:40:37Z",
  "updated_at": "2015-06-08T22:31:10Z",
  "closed_at": null,
  "body": null
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/2",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/2/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/2/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/2/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/2",
  "id": 86269119,
  "number": 2,
  "title": "Create Cluster in Database",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [ ],
  "state": "open",
  "locked": false,
  "assignee": {
  "login": "Berkana",
  "id": 1445825,
  "avatar_url": "https://avatars.githubusercontent.com/u/1445825?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Berkana",
  "html_url": "https://github.com/Berkana",
  "followers_url": "https://api.github.com/users/Berkana/followers",
  "following_url": "https://api.github.com/users/Berkana/following{/other_user}",
  "gists_url": "https://api.github.com/users/Berkana/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Berkana/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Berkana/subscriptions",
  "organizations_url": "https://api.github.com/users/Berkana/orgs",
  "repos_url": "https://api.github.com/users/Berkana/repos",
  "events_url": "https://api.github.com/users/Berkana/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Berkana/received_events",
  "type": "User",
  "site_admin": false
  },
  "milestone": null,
  "comments": 0,
  "created_at": "2015-06-08T17:40:09Z",
  "updated_at": "2015-06-08T22:31:19Z",
  "closed_at": null,
  "body": null
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/1",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/1/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/1/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/1/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/1",
  "id": 86269044,
  "number": 1,
  "title": "Create Issue in Database",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [ ],
  "state": "open",
  "locked": false,
  "assignee": {
  "login": "JustinWebb",
  "id": 442978,
  "avatar_url": "https://avatars.githubusercontent.com/u/442978?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/JustinWebb",
  "html_url": "https://github.com/JustinWebb",
  "followers_url": "https://api.github.com/users/JustinWebb/followers",
  "following_url": "https://api.github.com/users/JustinWebb/following{/other_user}",
  "gists_url": "https://api.github.com/users/JustinWebb/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/JustinWebb/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/JustinWebb/subscriptions",
  "organizations_url": "https://api.github.com/users/JustinWebb/orgs",
  "repos_url": "https://api.github.com/users/JustinWebb/repos",
  "events_url": "https://api.github.com/users/JustinWebb/events{/privacy}",
  "received_events_url": "https://api.github.com/users/JustinWebb/received_events",
  "type": "User",
  "site_admin": false
  },
  "milestone": null,
  "comments": 0,
  "created_at": "2015-06-08T17:39:58Z",
  "updated_at": "2015-06-08T22:31:25Z",
  "closed_at": null,
  "body": "Add issue entry and corresponding node"
  }
];

var users = [
  {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Katrina Uychaco",
  "company": "",
  "blog": "",
  "location": "",
  "email": "kuychaco@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 43,
  "public_gists": 0,
  "followers": 25,
  "following": 1,
  "created_at": "2014-06-17T07:30:41Z",
  "updated_at": "2015-05-30T04:48:50Z"
  },
  {
  "login": "Berkana",
  "id": 1445825,
  "avatar_url": "https://avatars.githubusercontent.com/u/1445825?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Berkana",
  "html_url": "https://github.com/Berkana",
  "followers_url": "https://api.github.com/users/Berkana/followers",
  "following_url": "https://api.github.com/users/Berkana/following{/other_user}",
  "gists_url": "https://api.github.com/users/Berkana/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Berkana/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Berkana/subscriptions",
  "organizations_url": "https://api.github.com/users/Berkana/orgs",
  "repos_url": "https://api.github.com/users/Berkana/repos",
  "events_url": "https://api.github.com/users/Berkana/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Berkana/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Austin Liu",
  "company": "",
  "blog": "",
  "location": "United States",
  "email": "berkamin@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 10,
  "public_gists": 0,
  "followers": 27,
  "following": 1,
  "created_at": "2012-02-17T07:40:44Z",
  "updated_at": "2015-05-11T16:45:12Z"
  },
  {
  "login": "JustinWebb",
  "id": 442978,
  "avatar_url": "https://avatars.githubusercontent.com/u/442978?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/JustinWebb",
  "html_url": "https://github.com/JustinWebb",
  "followers_url": "https://api.github.com/users/JustinWebb/followers",
  "following_url": "https://api.github.com/users/JustinWebb/following{/other_user}",
  "gists_url": "https://api.github.com/users/JustinWebb/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/JustinWebb/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/JustinWebb/subscriptions",
  "organizations_url": "https://api.github.com/users/JustinWebb/orgs",
  "repos_url": "https://api.github.com/users/JustinWebb/repos",
  "events_url": "https://api.github.com/users/JustinWebb/events{/privacy}",
  "received_events_url": "https://api.github.com/users/JustinWebb/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Justin Webb",
  "company": "",
  "blog": "",
  "location": "",
  "email": "jw@justinwebb.io",
  "hireable": false,
  "bio": null,
  "public_repos": 6,
  "public_gists": 0,
  "followers": 34,
  "following": 16,
  "created_at": "2010-10-17T18:31:39Z",
  "updated_at": "2015-05-12T01:54:59Z"
  },
  {
  "login": "cwhwang1986",
  "id": 8173733,
  "avatar_url": "https://avatars.githubusercontent.com/u/8173733?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/cwhwang1986",
  "html_url": "https://github.com/cwhwang1986",
  "followers_url": "https://api.github.com/users/cwhwang1986/followers",
  "following_url": "https://api.github.com/users/cwhwang1986/following{/other_user}",
  "gists_url": "https://api.github.com/users/cwhwang1986/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/cwhwang1986/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/cwhwang1986/subscriptions",
  "organizations_url": "https://api.github.com/users/cwhwang1986/orgs",
  "repos_url": "https://api.github.com/users/cwhwang1986/repos",
  "events_url": "https://api.github.com/users/cwhwang1986/events{/privacy}",
  "received_events_url": "https://api.github.com/users/cwhwang1986/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Charlie Hwang",
  "company": "",
  "blog": "",
  "location": "",
  "email": "cwhwang1986@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 9,
  "public_gists": 0,
  "followers": 23,
  "following": 2,
  "created_at": "2014-07-15T21:30:16Z",
  "updated_at": "2015-05-29T18:55:17Z"
  }
];

var labels = [
  {
  'url': 'https://api.github.com/repos/relentlessbreakfast/sampleGraph/labels/bug',
  'name': 'bug',
  'color': 'fc2929'
  },
  {
  'url': 'https://api.github.com/repos/relentlessbreakfast/sampleGraph/labels/duplicate',
  'name': 'duplicate',
  'color': 'cccccc'
  },
  {
  'url': 'https://api.github.com/repos/relentlessbreakfast/sampleGraph/labels/enhancement',
  'name': 'enhancement',
  'color': '84b6eb'
  },
  {
  'url': 'https://api.github.com/repos/relentlessbreakfast/sampleGraph/labels/help%20wanted',
  'name': 'help wanted',
  'color': '159818'
  },
  {
  'url': 'https://api.github.com/repos/relentlessbreakfast/sampleGraph/labels/invalid',
  'name': 'invalid',
  'color': 'e6e6e6'
  },
  {
  'url': 'https://api.github.com/repos/relentlessbreakfast/sampleGraph/labels/question',
  'name': 'question',
  'color': 'cc317c'
  },
  {
  'url': 'https://api.github.com/repos/relentlessbreakfast/sampleGraph/labels/wontfix',
  'name': 'wontfix',
  'color': 'ffffff'
  }
];

var graph1 = {
  "1": {
    "id": 1,
    "type": "cluster",
    "parent_cluster": 0,
    "cluster_id": 1,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 1,
      "abbrev": "ROOT",
      "name": "Project Root",
      "description": "Cluster of entire project",
      "endpoints": [2,3],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "2": {
    "id": 2,
    "type": "enter",
    "parent_cluster": 1,
    "cluster_id": null,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null
  },
  "3": {
    "id": 3,
    "type": "exit",
    "parent_cluster": 1,
    "cluster_id": null,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null
  },
  "4": {
    "id": 4,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 2,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 2,
      "abbrev": "Auth",
      "name": "Authentication",
      "description": "Set up authentication",
      "endpoints": [5,6],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "7": {
    "id": 7,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 3,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 3,
      "abbrev": "DB",
      "name": "Database",
      "description": "Set up database",
      "endpoints": [8,9],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "10": {
    "id": 10,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 4,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 4,
      "abbrev": "ExAPI",
      "name": "Github API",
      "description": "Pull info from Github API",
      "endpoints": [11,2],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "13": {
    "id": 13,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 5,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 5,
      "abbrev": "View Plan",
      "name": "Plan out User Interface",
      "description": "Mock up user interface",
      "endpoints": [14,5],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "16": {
    "id": 16,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 6,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 6,
      "abbrev": "Model",
      "name": "Design data model",
      "description": "Set up app models",
      "endpoints": [17,8],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "19": {
    "id": 19,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 7,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 7,
      "abbrev": "Contr",
      "name": "Data controller",
      "description": "Set up data controller",
      "endpoints": [20,1],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "22": {
    "id": 22,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 8,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 8,
      "abbrev": "View",
      "name": "Implement angular front end",
      "description": "Create angular front end",
      "endpoints": [23,4],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "25": {
    "id": 25,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 9,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 9,
      "abbrev": "Styling",
      "name": "Polish the UI",
      "description": "CSS makeover",
      "endpoints": [26,7],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "28": {
    "id": 28,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 10,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 10,
      "abbrev": "Integ",
      "name": "Integration",
      "description": "Combine all parts",
      "endpoints": [29,0],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "31": {
    "id": 31,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 11,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 11,
      "abbrev": "Deploy",
      "name": "Deploy the application",
      "description": "Deploy the application",
      "endpoints": [32,3],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "parent_cluster": "1",
  "enter": 2,
  "exit": 3,
  "deleted": []
};

var graph_removed_19 = {
  "1": {
    "id": 1,
    "type": "cluster",
    "parent_cluster": 0,
    "cluster_id": 1,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 1,
      "abbrev": "ROOT",
      "name": "Project Root",
      "description": "Cluster of entire project",
      "endpoints": [2,3],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "2": {
    "id": 2,
    "type": "enter",
    "parent_cluster": 1,
    "cluster_id": null,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null
  },
  "3": {
    "id": 3,
    "type": "exit",
    "parent_cluster": 1,
    "cluster_id": null,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null
  },
  "4": {
    "id": 4,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 2,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 2,
      "abbrev": "Auth",
      "name": "Authentication",
      "description": "Set up authentication",
      "endpoints": [5,6],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "7": {
    "id": 7,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 3,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 3,
      "abbrev": "DB",
      "name": "Database",
      "description": "Set up database",
      "endpoints": [8,9],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "10": {
    "id": 10,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 4,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 4,
      "abbrev": "ExAPI",
      "name": "Github API",
      "description": "Pull info from Github API",
      "endpoints": [11,2],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "13": {
    "id": 13,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 5,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 5,
      "abbrev": "View Plan",
      "name": "Plan out User Interface",
      "description": "Mock up user interface",
      "endpoints": [14,5],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "16": {
    "id": 16,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 6,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 6,
      "abbrev": "Model",
      "name": "Design data model",
      "description": "Set up app models",
      "endpoints": [17,8],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  // "19": {
  // "id": 19,
  // "type": "cluster",
  // "parent_cluster": 1,
  // "cluster_id": 7,
  // "issue_id": null,
  // "upstream_nodes": null,
  // "downstream_nodes": null,
  // "cluster": {
  // "id": 7,
  // "abbrev": "Contr",
  // "name": "Data controller",
  // "description": "Set up data controller",
  // "endpoints": [
  // 20,
  // 21
  // ],
  // "creator": 7910250,
  // "children_count": 5,
  // "children_complete": 0
  // }
  // },
  "22": {
    "id": 22,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 8,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 8,
      "abbrev": "View",
      "name": "Implement angular front end",
      "description": "Create angular front end",
      "endpoints": [23,4],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "25": {
    "id": 25,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 9,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 9,
      "abbrev": "Styling",
      "name": "Polish the UI",
      "description": "CSS makeover",
      "endpoints": [26,7],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "28": {
    "id": 28,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 10,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 10,
      "abbrev": "Integ",
      "name": "Integration",
      "description": "Combine all parts",
      "endpoints": [29,0],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "31": {
    "id": 31,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 11,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 11,
      "abbrev": "Deploy",
      "name": "Deploy the application",
      "description": "Deploy the application",
      "endpoints": [32,3],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "parent_cluster": "1",
  "enter": 2,
  "exit": 3,
  "deleted": [7]
};

var graph2 = {
  "7": {
    "id": 7,
    "type": "cluster",
    "parent_cluster": 1,
    "cluster_id": 3,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null,
    "cluster": {
      "id": 3,
      "abbrev": "DB",
      "name": "Database",
      "description": "Set up database",
      "endpoints": [8,9],
      "creator": 7910250,
      "children_count": 5,
      "children_complete": 0
    }
  },
  "20": {
    "id": 20,
    "type": "enter",
    "parent_cluster": 7,
    "cluster_id": null,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null
  },
  "21": {
    "id": 21,
    "type": "exit",
    "parent_cluster": 7,
    "cluster_id": null,
    "issue_id": null,
    "upstream_nodes": null,
    "downstream_nodes": null
  },
  "34": {
    "id": 34,
    "type": "issue",
    "parent_cluster": 7,
    "cluster_id": null,
    "issue_id": 86269811,
    "upstream_nodes": null,
    "downstream_nodes": null,
  "issue": {
  "id": 86269811,
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/6",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/6/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/6/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/6/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/6",
  "number_github": 6,
  "title": "Create JSON Object",
  "creator": 7910250,
  "labels": null,
  "state": "open",
  "locked": false,
  "assignee": 1445825,
  "comments": 0,
  "created_at": "2015-06-08T17:41:50Z",
  "updated_at": "2015-06-08T22:30:47Z",
  "closed_at": "null",
  "body": "Create node objects with appropriate issue or cluster data"
  }
  },
  "35": {
    "id": 35,
    "type": "issue",
    "parent_cluster": 7,
    "cluster_id": null,
    "issue_id": 86269541,
    "upstream_nodes": null,
    "downstream_nodes": null,
  "issue": {
  "id": 86269541,
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/5",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/5/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/5/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/5/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/5",
  "number_github": 5,
  "title": "Delete Record",
  "creator": 7910250,
  "labels": null,
  "state": "open",
  "locked": false,
  "assignee": 8173733,
  "comments": 0,
  "created_at": "2015-06-08T17:41:08Z",
  "updated_at": "2015-06-08T22:30:57Z",
  "closed_at": "null",
  "body": "Remove nodes from database"
  }
  },
  "36": {
    "id": 36,
    "type": "issue",
    "parent_cluster": 7,
    "cluster_id": null,
    "issue_id": 86269457,
    "upstream_nodes": null,
    "downstream_nodes": null,
  "issue": {
  "id": 86269457,
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/4",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/4/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/4/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/4/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/4",
  "number_github": 4,
  "title": "Update Record",
  "creator": 7910250,
  "labels": null,
  "state": "open",
  "locked": false,
  "assignee": 442978,
  "comments": 0,
  "created_at": "2015-06-08T17:40:55Z",
  "updated_at": "2015-06-08T22:31:03Z",
  "closed_at": "null",
  "body": "null"
  }
  },
  "37": {
    "id": 37,
    "type": "issue",
    "parent_cluster": 7,
    "cluster_id": null,
    "issue_id": 86269344,
    "upstream_nodes": null,
    "downstream_nodes": null,
  "issue": {
  "id": 86269344,
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/3",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/3/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/3/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/3/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/3",
  "number_github": 3,
  "title": "Read Record from Database",
  "creator": 7910250,
  "labels": null,
  "state": "open",
  "locked": false,
  "assignee": 7910250,
  "comments": 0,
  "created_at": "2015-06-08T17:40:37Z",
  "updated_at": "2015-06-08T22:31:10Z",
  "closed_at": "null",
  "body": "null"
  }
  },
  "38": {
    "id": 38,
    "type": "issue",
    "parent_cluster": 7,
    "cluster_id": null,
    "issue_id": 86269119,
    "upstream_nodes": null,
    "downstream_nodes": null,
  "issue": {
  "id": 86269119,
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/2",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/2/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/2/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/2/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/2",
  "number_github": 2,
  "title": "Create Cluster in Database",
  "creator": 7910250,
  "labels": null,
  "state": "open",
  "locked": false,
  "assignee": 1445825,
  "comments": 0,
  "created_at": "2015-06-08T17:40:09Z",
  "updated_at": "2015-06-08T22:31:19Z",
  "closed_at": "null",
  "body": "null"
  }
  },
  "39": {
    "id": 39,
    "type": "issue",
    "parent_cluster": 7,
    "cluster_id": null,
    "issue_id": 86269044,
    "upstream_nodes": null,
    "downstream_nodes": null,
  "issue": {
  "id": 86269044,
  "url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/1",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/1/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/1/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/WebApp/issues/1/events",
  "html_url": "https://github.com/relentlessbreakfast/WebApp/issues/1",
  "number_github": 1,
  "title": "Create Issue in Database",
  "creator": 7910250,
  "labels": null,
  "state": "open",
  "locked": false,
  "assignee": 442978,
  "comments": 0,
  "created_at": "2015-06-08T17:39:58Z",
  "updated_at": "2015-06-08T22:31:25Z",
  "closed_at": "null",
  "body": "Add issue entry and corresponding node"
  }
  },
  "parent_cluster": "7",
  "enter": 20,
  "exit": 21,
  "deleted": []
  };

var clusters = [
  {
    abbrev: 'ROOT',
    name: 'Project Root',
    description: 'Cluster of entire project',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'Auth',
    name: 'Authentication',
    description: 'Set up authentication',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'DB',
    name: 'Database',
    description: 'Set up database',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'ExAPI',
    name: 'Github API',
    description: 'Pull info from Github API',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'View Plan',
    name: 'Plan out User Interface',
    description: 'Mock up user interface',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'Model',
    name: 'Design data model',
    description: 'Set up app models',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'Contr',
    name: 'Data controller',
    description: 'Set up data controller',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'View',
    name: 'Implement angular front end',
    description: 'Create angular front end',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'Styling',
    name: 'Polish the UI',
    description: 'CSS makeover',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'Integ',
    name: 'Integration',
    description: 'Combine all parts',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  },
  {
    abbrev: 'Deploy',
    name: 'Deploy the application',
    description: 'Deploy the application',
    creator: 7910250,
    children_count: 5,
    children_complete: 0
  }
];


module.exports.users = users;
module.exports.issues = issues;
module.exports.labels = labels;
module.exports.graph1 = graph1;
module.exports.graph2 = graph2;
module.exports.clusters = clusters;
